# Generated by Django 5.0.7 on 2025-07-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_number',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
