# Generated by Django 5.0.7 on 2025-07-02 11:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_product_image_alter_product_sales_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='number_of_personals',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='product',
            name='info',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
