# Generated by Django 5.0.7 on 2025-07-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_alter_order_phone_number_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_number',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
